FROM rocker/r-ver:4.3.2

# Set the working directory
WORKDIR /app

# Copy files
COPY Data /app/Data
COPY client.sh /app/run.sh

# Make the script executable
RUN chmod +x /app/run.sh

# Set the entrypoint to execute the script
ENTRYPOINT ["/app/run.sh"]
